-- Daily Dew Shiloh July 2026 seed.
-- Run this after supabase-schema.sql in the Supabase SQL Editor.
begin;

insert into public.editions (slug, title, theme, month, year, language, status, introduction)
values (
  'shiloh-july-2026',
  'Shiloh',
  'Genesis 1:28 Era',
  7, 2026, 'en', 'draft',
  'The July edition journeys through the blessing, fruitfulness, multiplication, restoration, and dominion of Genesis 1:28.'
)
on conflict (slug) do update set updated_at = now();

insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 1, 'Wondersday 1st', 'The Blessing Before The Command', 'And God blessed them, and God said unto them, Be fruitful, and multiply, and replenish the earth, and subdue it: and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth. – Genesis 1:28 KJV', 'One of the greatest revelations in scripture is that God blessed man before He gave him an assignment. The first thing Adam received was not work, responsibility, or authority, it was the blessing. This blessing was heaven''s empowerment to succeed in every divine assignment. Fruitfulness, multiplication, replenishment, subduing, and dominion are not human achievements; they are manifestations of God''s blessing at work in a yielded life. Every believer in Christ has been called to function from this position of divine empowerment rather than human effort. When you understand that you are already blessed in Christ, you stop striving for acceptance and begin manifesting God''s original plan. Fellow Labourer in Christ, refuse to approach this month with a mentality of lack, fear, or limitation. You are carrying the blessing of God, and that blessing distinguishes you wherever you go. Let every decision, prayer, and action this month flow from the consciousness that heaven has already spoken well concerning you. As you remain connected to God through obedience, prayer, and His Word, the blessing upon your life will produce visible fruit, supernatural increase, divine restoration, victory over eve ry opposition, and unquestionable dominion. This is your season to manifest God''s original intention for your life. Great Grace!', '["Ephesians 1:3", "Deuteronomy 28:1 –13", "Psalm 1:1 –3", "2 Corinthians 9:8"]'::jsonb, 'God''s blessing is the divine empowerment that makes His commands possible.', 'I am blessed by God and empowered for fruitfulness. I shall multiply in grace, wisdom, influence, and resources. Every loss is restored, every opposition is subdued, and I walk in dominion through Christ Jesus. This month, I manifest God''s original purpose for my life. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 2, 'Triumphday 2nd', 'The Mystery Of Fruitfulness', 'And God blessed them, and God said unto them, Be fruitful… – Genesis 1:28 KJV', 'Fruitfulness is the first expectation God placed upon humanity. Notice that before God spoke of multiplication, replenishment, or dominion, He first commanded man to be fruitful. This is because multiplication is impossible without fruitfulness. In scripture, fruitfulness is more than having children or possessing material abundance – It is the ability to consistently produce results that glorify God. A fruitful believer produces the fruit of the Spirit (ref: Galatians 5:22-23), wins souls (ref: John 15:16), grows in wisdom (ref: Proverbs 3:13 -18), influences generations, and leaves behind a godly legacy. Fruitfulness is the visible evidence that divine life is actively flowing through a believer. Fellow Labourer in Christ, never mistake activity for fruitfulness. Many are busy, yet they produce nothing of eternal value. God is not impressed by motion; He is pleased by results that originate from His Spirit. Examine your life today, is your prayer life fruitful? Is your ministry fruitful? Is your business, family, studies, or career producing God -honouring results? Whatever remains connected to Christ cannot remain barren. Therefore, remain rooted in His presence, abide in His Word, and yield yourself to the Holy Spirit. I pray for you; the life of God within you possesses everything necessary to make you fruitful in every dimension of life in the name of Jesus. Great Grace!', '["John 15:1–8", "Psalm 92:12–15", "Colossians 1:10", "Galatians 5:22–23"]'::jsonb, 'God measures your life by fruitfulness, not by busyness.', 'I refuse every form of barrenness. I am fruitful spiritually, mentally, financially, ministerial, and physically. Everywhere I go, I produce lasting results that glorify God. My life is a testimony of divine productivity, in Jesus’ Name. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 3, 'Faithday 3rd', 'The Law Of Multiplication', 'And God blessed them, and God said unto them, Be fruitful, and multiply... – Genesis 1:28', 'God never intended His blessings to remain at the level of addition. The Kingdom of God operates by multiplication. A single seed produces a harvest. One disciple raises many disciples. One anointed man equips many labourers. Throughout scripture, God consistently demonstrates His nature through multiplication. He multiplied Abraham into nations, multiplied Israel in Egypt despite oppression, multiplied the widow''s oil, multiplied five loaves to feed thousands, and multiplied grace in the New Testament Churc h. Whenever God is involved, increase becomes inevitable. Multiplication is the supernatural enlargement of what has already become fruitful. Fellow Labourer in Christ, never despise what God has already placed in your hands. Heaven does not multiply what is ignored; it multiplies what is surrendered. The little gift, the small opportunity, the humble beginning, and the hidden season are all raw materials for divine multiplication. Faithfulness attracts increase. Gratitude preserves increase. Obedience accelerates increase. Refuse to compare your beginning with another person''s harvest. I pray for you; as you continue serving diligently, the God who multiplies seeds will multiply your influence, resources, wisdom, opportunities, and impact upon the earth in Jesus'' name. Great Grace!', '["Matthew 25:14–30", "Mark 6:37–44", "2 Corinthians 9:10", "Acts 6:7"]'::jsonb, 'God multiplies what is faithfully surrendered to Him.', 'The grace of multiplication rests upon my life. Every good thing God has planted within me shall increase beyond human expectation. I multiply in wisdom, influence, favour, resources, and kingdom impact, in Jesus'' Name. Hallelujah!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 4, 'Sabbathday 4th', 'Replenish The Wasted Places', '‘And I will restore to you the years that the locust hath eaten, the cankerworm, and the caterpillar, and the palmerworm… – Joel 2:25', 'The command to replenish the earth reveals that God’s nature is restorative. To replenish means to refill, restore, recover, and bring back to fullness what has become empty. Sin introduced loss into creation, but redemption introduced restoration. Throughout scripture, God reveals Himself as the restorer of broken destinies, wasted years, shattered hopes, and forgotten dreams. He restored Job’s fortunes, revived Naomi’s household, restored Peter after failure, and raised dry bones into a mighty army. Our God never abandons empty places; He fills them again with His glory. Fellow Labourer in Christ, perhaps you have experienced delays, disappointments, financial setbacks, spiritual dryness, or missed opportunities. The God who commanded replenishment has not forgotten you. He specializes in restoring what men consider irrecoverable. Refuse to dwell on yesterday’s losses. Lift up your voice for a minute and call on the God of restoration. I pray for you; as you believe in His promises and align yourself to His will, supernatural recovery is yours throughout this month. Every s eason surrendered to Him becomes a testimony for you. What took years to lose will be restored by divine intervention in a moment in the name of Jesus. Great Grace!', '["Joel 2:21–27", "Isaiah 61:7", "Job 42:10", "Psalm 126:1–6"]'::jsonb, 'God’s restoration is never merely replacement; it is divine compensation.', 'Every wasted season is restored. Every lost opportunity returns by divine mercy. The Lord replenishes my strength, resources, joy, peace, relationships, and purpose. I recover all, in Jesus’ Name. Glory!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 5, 'Sacredday 5th', 'The Mandate to Subdue', '…Replenish the earth, and subdue it: and have dominion... – Genesis 1:28', 'The word subdue means to bring under control, to conquer, to overcome resistance, and to establish divine order where chaos exists. God never promised Adam a resistance -free earth. Instead, He empowered him to overcome every resistance he would encounter. Likewise, every believer will face opposition, whether from the flesh, the world, or the kingdom of darkness, but we have been equipped with divine authority through Christ. To subdue is not to dominate people but to overcome every force that seeks to hinder God''s ordination in our lives. Through prayer, faith, obedience, and the authority of God''s Word, every mountain can be brought low. Fellow Labourer in Christ, never surrender the territory that God has assigned to you. Whether it is your spiritual life, family, ministry, career, health, or calling, refuse to permit the enemy to occupy what belongs to the Lord. Every challenge before you is an opportunity to demonstrate the victory already secured through Christ. Do not negotiate with fear, compromise with sin, or retreat because of opposition. Rise in the authority of your heavenly position. I pray for you; as you walk in obedience and exercise your God-given authority, every contradicting voice shall be silenced, every obstacle shall bow, and every resistance shall give way before the power of God in Jesus'' name. Great Grace!', '["Luke 10:19", "Joshua 1:3–9", "Romans 8:37", "1 John 4:4"]'::jsonb, 'Every divine assignment carries sufficient grace to overcome every opposition.', 'I subdue every work of darkness assigned against my life. By the authority of Jesus Christ, every opposition bows before me. I walk in total victory, I possess my inheritance, and I establish God''s Kingdom wherever He sends me. Hallelujah!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 6, 'Mercyday 6th', 'The Life of Dominion', '…and have dominion over the fish of the sea, and over the fowl of the air, and over every living thing that moveth upon the earth. – Genesis 1:28', 'Dominion is the climax of God’s original mandate to mankind. After blessing man, commanding fruitfulness, multiplication, replenishment, and subduing, God crowned it with dominion. Dominion is not oppression; it is righteousness stewardship under the authority of God. It is the ability to govern circumstances without being governed by them. Before the fall, Adam was not intimidated by creation because he carried the authority of the Creator. He named the animals, cultivated the garden, and functioned as God’s representative on the earth. Through the finished work of Christ the last Adam; that dominion has been restored to every believer. Dominion is therefore the practical expression of Christ’s victory manifested through His Church and the saints. Fellow Labourer in Christ, refuse to live beneath your spiritual position. You were not redeemed merely to escape hell; you were redeemed to represent Heaven. A believer walking in dominion does not allow fear to dictate decisions, sin to control his life, or the systems of this world to define his identity. Dominion begins within before it is manifested without. A man who cannot govern his appetite cannot govern territories. A woman who cannot rule over anger cannot effectively rule over circumstances. Allow the Holy Spirit to establish His government in your heart, and His authority will naturally flow through your life. I pray for you; in this month, wherever darkness has attempted to reign, let the light of Christ in you establish the government of Heave n in the name of Jesus. Great Grace!', '["Romans 5:17", "Luke 10:19", "Psalm 8:4–8", "Revelation 5:10"]'::jsonb, 'True dominion begins with self -government under the government of God.', 'I walk in the dominion of Christ. Sin shall not rule over me. Fear shall not master me. I reign over circumstances through the authority of Jesus Christ. Every area of my life reflects the government of Heaven. I am more than a conqueror. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 7, 'Truthday 7th', 'Abide to Abound', 'I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing. – John 15:5', 'Every branch has only one responsibility, to remain connected to the vine. It does not struggle to produce fruits; it simply abides, and fruits becomes the natural outcome of that relationship. This is one of the greatest mysteries of the Kingdom. Many believers spend their energy trying to manufacture results instead of cultivating intimacy with Christ. Fruitfulness is never produced by human effort alone; it is the overflow of divine life. The sap that nourishes the branch is invisible from outer view, yet its evidence becomes visible in the fruit. Likewise, our secret fellowship with God eventually becomes public manifestation. Prayer, meditation on the Word, worship, and obedience are not religious activities; they are the channels through which the life of Christ continually flows into the believer. Fellow Labourer in Christ, if you desire unusual results, deepen your communion with God. Public victories are born from private encounters. Do not become so occupied with ministry that you neglect the Master. Do not pursue gifts while abandoning the Giver. There is no substitute for daily fellowship with the Holy Spirit. The believer who abides in Christ carries a freshness that the world cannot explain. Even in seasons of drought, he remains fruitful because his source is not earthly but heavenly. I pray for you; your greatest pursuit this month will be intimacy with God, and as you do so every other blessing will become the fruit of that relationship in Jesus’ name. Great Grace!', '["Psalm 1:1 –3", "Jeremiah 17:7 –8", "Colossians 2:6–7", "Ephesians 3:16–19"]'::jsonb, 'The secret place is the birthplace of public fruitfulness.', 'I abide in Christ continually. His life flows through me, and I bring forth lasting fruits. I shall never be spiritually dry, emotionally empty, or physically barren. My life overflows with the abundance of God’s presence. Hallelujah!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 8, 'Wondersday 8th', 'The Power of the Blessing', 'The blessing of the LORD, it maketh rich, and he addeth no sorrow with it. – Proverbs 10:22', 'The blessing of God is more than kind words or good wishes; it is a spiritual force released by God that empowers a person to prosper according to His purpose. In Genesis 1:28, God did not merely encourage Adam, He blessed him. That blessing became the divine ability to fulfil every assignment Heaven had given. Throughout Scripture, we see that wherever the blessing of God rested, impossible things became possible. Abraham became the father of nations, Isaac prospered during famine, Joseph rul ed in a foreign land, and David rose from shepherd to king. The blessing distinguishes ordinary people for extraordinary exploits because it carries the favour, presence, and power of God. Fellow Labourer in Christ, never underestimate what rests upon your life because you belong to Christ. The blessing is not determined by your location, background, economy, or family history. It flows from your covenant relationship with God. Even when circumstances appear contrary, the blessing is working behind the scenes to align events in your favour. Therefore, refuse to speak words that contradict the blessing. Declare God’s promises over your life daily. Walk in obedience, maintain a thankful heart, and expect divine interventions. I pray for you; let the blessing of God open doors that qualifications cannot open, preserve what human wisdom cannot preserve, and establish what human strength cannot establish in Jesus’ name. Great Grace!', '["Genesis 12:1–3", "Deuteronomy 28:1–14", "Ephesians 1:3", "Galatians 3:13–14"]'::jsonb, 'The blessing is Heaven’s empowerment for earthly accomplishment.', 'The blessing of the Lord is evident upon my life. I prosper without sorrow. I am favoured, preserved, distinguished and empowered to fulfil my divine assignment. Everywhere I go, the blessing speaks on my behalf. Glory!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 9, 'Triumphday 9th', 'From Seed to Harvest', 'In the morning sow thy seed, and in the evening withhold not thine hand: for thou knowest not whether shall prosper, either this or that, or whether they both shall be alike good. – Ecclesiastes 11:6', 'God’s Kingdom operates on the principle of seedtime and harvest. Every harvest begins with a seed, and every seed carries within it the potential for multiplication. This principle governs every aspect of life. As we saw in the month of seeds and investment, our words are seeds, our actions are seeds, our prayers are seeds, our giving is seed, and even our character is continually sowing into our future. No farmer expects a harvest without planting, and no believer should expect a fruitful life while neglect ing the discipline of sowing into the Kingdom. The remarkable thing about God’s economy is that He often hides great destinies inside small beginnings. A single seed may appear insignificant, but under God’s blessing it can become a mighty forest. Fellow Labourer in Christ, do not become weary because your harvest has not yet appeared. Every seed has an appointed season of manifestation. Continue sowing righteousness, kindness, generosity, excellence, prayer, and faithfulness. Resist the temptation to abandon your field because of temporary delays. The God who watches over His Word also watches over every seed sown in obedience. In due season, what has been hidden beneath the soil will break forth with undeniable increase. As you harvest fruits this month, do not forget to intentional sow more seeds for the harvest of tomorrow is determined by the seeds you plant today. Great Grace!', '["Genesis 8:22", "Galatians 6:7 –9", "2 Corinthians 9:6 –11", "Mark 4:26–29"]'::jsonb, 'Your future harvest is hidden inside today’s faithful seed.', 'Every good seed I have sown shall produce an abundant harvest. I shall not labour in vain. My obedience, prayers, sacrifices, and service shall yield multiplied returns according to God’s perfect will. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 10, 'Faithday 10th', 'Created To Cultivate', 'And the LORD God took the man, and put him into the garden of Eden to dress it and to keep it. - Genesis 2:15 KJV', 'Before sin entered the world, work already existed. This reveals that work is not a curse; it is a divine responsibility. Adam was placed in Eden not merely to enjoy its beauty but to cultivate and preserve it. The blessing of Genesis 1:28 was never intended to promote laziness. God''s pattern is blessing followed by responsibility, favour followed by stewardship, and increase followed by accountability. The Garden of Eden represents every assignment, opportunity, relationship, ministry, busi ness, career, and gift entrusted to us by God. Nothing flourishes without cultivation. Even the most fertile ground becomes overgrown when neglected. Likewise, every divine promise requires diligent cooperation with God. Fellow Labourer in Christ, ask yourself, " what garden has God entrusted to me?" It may be your family, your ministry, your profession, your business, your education, or the spiritual gifts deposited within you. Whatever God has placed in your hands deserves your excellence. Never pray for enlargement while neglecting your present assignment. Many seek another vineyard while abandoning the one already entrusted to them. Faithfulness in little is God''s pathway to much. Cultivate your prayer life. Develop your gifts. Improve your skills. Guard your cha racter. Protect your relationships. As you faithfully tend what God has given you, He will enlarge your borders and entrust you with greater responsibilities. Great Grace!', '["Proverbs 22:29", "Matthew 25:21", "Luke 16:10", "Colossians 3:23–24"]'::jsonb, 'God blesses what you cultivate, not what you neglect.', 'I receive grace to faithfully cultivate every assignment God has committed into my hands. I reject laziness, negligence, and mediocrity. Through diligence and the blessing of God, my life shall continually flourish, in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 11, 'Sabbathday 11th', 'The Blessing Of Capacity', 'Enlarge the place of thy tent, and let them stretch forth the curtains of thine habitations: spare not, lengthen thy cords, and strengthen thy stakes; For thou shalt break forth on the right hand and on the left... - Isaiah 54:2-3 KJV', 'God never pours new wine into old wineskins. Before He enlarges your harvest, He enlarges your capacity. Capacity is your ability to receive, contain, manage, and sustain what God desires to release into your life. Many believers pray for increase but resist the process of growth. Yet God is more interested in preparing the vessel than merely releasing the blessing.\n\nAbraham''s capacity was enlarged through years of walking with God. Joseph''s leadership was forged in slavery and prison before the palace. David''s heart was prepared in lonely fields before the throne. Heaven enlarges the man before enlarging his territory. Fellow Labourer in Christ, do not despise seasons of preparation. The trials, corrections, teachings, and disciplines you are presently experiencing are enlarging your spiritual capacity.\n\nEvery book you read, every lesson you learn, every act of obedience, every sacrifice, and every prayer is stretching your ability to carry greater glory. Refuse to settle for yesterday''s level of understanding. Grow in wisdom. Grow in faith. Grow in character. Grow in competence. The greater your capacity, the greater your usefulness in the Kingdom. God desires to entrust much to those who have become mature enough to carry it without pride or compromise. Great Grace!', '["Isaiah 54:2–3", "Luke 12:48", "2 Timothy 2:20–21", "Ephesians 3:20"]'::jsonb, 'Your capacity determines the measure of your stewardship.', 'Lord, enlarge my capacity. Expand my faith, my wisdom, my understanding, and my influence. Prepare me for greater assignments and greater manifestations of Your glory. I shall not break under the weight of my next level, in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 12, 'Sacredday 12th', 'The Mystery Of Kingdom Influence', 'Ye are the salt of the earth... Ye are the light of the world. A city that is set on an hill cannot be hid. - Mathew 5:13-15 KJV', 'God''s command to "replenish the earth" and "have dominion" was never confined to occupying physical space; it also meant influencing culture with Heaven''s values. Salt preserves, seasons, and prevents corruption. Light reveals, guides, and dispels darkness. Jesus intentionally used these two illustrations because they describe the believer''s assignment in the world. We are not called to escape society but to transform it. Dominion is not measured by titles or positions; it is measured by influence. Wherever God''s people carry His presence, righteousness should replace corruption, hope should overcome despair, and truth should silence deception. One Joseph preserved an entire civilization. One Esther rescued a nation. One Daniel changed the policies of kingdom s because they carried the influence of Heaven. Fellow Labourer in Christ, never underestimate the impact your life can make. You may be the only Bible someone ever reads. Your integrity may open doors that preaching alone cannot. Your excellence at work may become the platform through which Christ is r evealed. Let your speech carry grace. Let your conduct reflect holiness. Let your decisions reveal wisdom. Refuse to blend into the darkness around you. Instead, become a visible expression of God''s Kingdom wherever He has planted you. When believers walk in righteousness and excellence, they become irresistible witnesses of God''s glory. Great Grace!', '["Daniel 6:1–5", "Philippians 2:14–16", "1 Peter 2:9–10", "Romans 12:2"]'::jsonb, 'Influence is dominion expressed through godly character.', 'I am the salt of the earth and the light of the world. Through my life, God''s wisdom, righteousness, and glory are revealed. I influence my generation for Christ and advance His Kingdom wherever I go. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 13, 'Mercyday 13th', 'The Law Of Increase', 'Of the increase of his government and peace there shall be no end, upon the throne of David, and upon his kingdom, to order it, and to establish it with judgment and with justice from henceforth even forever. - Isaiah 9:7 KJV', 'Increase is one of the undeniable characteristics of God''s Kingdom. Wherever God reigns, stagnation is not permitted. The Kingdom is continually advancing, continually expanding, and continually manifesting greater glory. This is why Genesis 1:28 commands us to "multiply." God is not merely interested in maintaining what He has already done; He delights in taking His people from glory to glory, strength to strength, and faith to faith.\n\nThe law of increase is rooted in God''s own nature. He created one man and produced nations. He planted one garden and intended it to replenish the earth. He anointed twelve disciples who turned the world upside down. Every genuine encounter with God should leave a believer growing in wisdom, character, influence, and spiritual authority.\n\nFellow Labourer in Christ, reject every mentality of stagnation. Refuse to become comfortable with yesterday''s victories while neglecting today''s opportunities. Growth is intentional. Your prayer life should increase. Your knowledge of Scripture should deepen. Your love for people should mature. Your excellence in service should improve. The greatest enemy of tomorrow''s increase is satisfaction with yesterday''s success. Keep stretching your faith. Keep learning. Keep serving. Keep believing. As you remain yielded to the Holy Spirit, He will continually enlarge your vision and empower you for greater assignments. Your latter days shall be greater than your former because the God you serve is the God of increase. Great Grace!', '["Proverbs 4:18", "2 Corinthians 3:18", "Psalm 115:14–15", "Acts 2:47"]'::jsonb, 'Where God rules, increase becomes a lifestyle.', 'I reject stagnation in every area of my life. I increase in grace, wisdom, favour, influence, resources, and spiritual authority. From this day forward, my path shines brighter and brighter unto the perfect day. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 14, 'Truthday 14th', 'The Mystery Of Divine Order', 'Let all things be done decently and in order." - 1 Corinthians 14:40 KJV', 'Before God commanded man to subdue the earth, He first demonstrated the principle of divine order in creation. Genesis chapter one reveals that nothing God created was random. Light came before vegetation. The heavens were arranged before the stars were placed in them. The earth was prepared before man was introduced. God established systems before introducing those who would function within them. This teaches us that dominion flourishes where order exists. Disorder weakens productivity, but order multiplies efficiency. Heaven operates through divine order, and every believer who desires lasting fruitfulness must embrace God''s systems. The Holy Spirit is not the author of confusion but of peace, clarity, and divine arrangement. Fellow Labourer in Christ, examine the systems of your life. Is there order in your prayer life? Is your time properly managed? Are your finances governed by biblical principles? Is your home built on godly values? Many people pray for breakthrough while living in disorder. Yet God''s blessings are often sustained through discipline. Create godly routines. Honour your commitments. Live with integrity. Be punctual. Plan wisely. Keep learning. Order is one of the greatest expressions of wisdom because it creates room for God to entrust greater responsibilities. This month, ask the Holy Spirit to rearrange every area of your life that has become disorganized, so that His purposes may flourish through you. Great Grace!', '["Genesis 1:1–31", "Proverbs 24:3–4", "Ecclesiastes 3:1", "James 3:16–18"]'::jsonb, 'Order is the environment where dominion thrives.', 'The wisdom of God establishes divine order in my life. Every area of confusion gives way to clarity. I walk in discipline, excellence, and divine arrangement. My life reflects the order of Heaven, in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 15, 'Wondersday 15th', 'Fruitful In Every Good Work', 'That ye might walk worthy of the Lord unto all pleasing, being fruitful in every good work, and increasing in the knowledge of God. - Colossians 1:10 KJV', 'God''s desire is not that His children should be fruitful in only one area of life while remaining barren in others. His purpose is comprehensive fruitfulness. A believer should exhibit fruit in character, prayer, ministry, family, relationships, finances, leadership, and service. The Christian life is not compartmentalized. The same Spirit who empowers us to preach also empowers us to love, forgive, lead, create, build, and serve with excellence. This is why Paul prayed that believe rs would be "fruitful in e very good work." True fruitfulness is the outward evidence of an inward transformation. It is impossible to genuinely know God without increasingly reflecting His nature. Fellow Labourer in Christ, do not settle for selective obedience. Allow Christ to influence every dimension of your life. Let your workplace reflect His integrity. Let your home reflect His love. Let your speech reflect His wisdom. Let your decisions reflect His righteousness. The world is waiting for believers whose lives consistently reveal the character of Christ. Remember, your greatest sermon is often not what you say but how you live. As you yield every area of your life to the Holy Spirit, He will make you fruitful beyond your imagination, and your life will become a living testimony of God''s transforming power. Great Grace!', '["John 15:8", "Titus 3:14", "Ephesians 2:10", "Philippians 1:11"]'::jsonb, 'The greatest fruit you can bear is a life that consistently reflects Christ.', 'I am fruitful in every good work. My life glorifies Christ in character, conduct, service, and purpose. I increase continually in the knowledge of God and manifest His nature everywhere I go. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 16, 'Triumphday 16th', 'Subduing Mental Strongholds', 'For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds; Casting down imaginations, and every high thing that exalteth itself against the knowledge of God, and bringing into captivity every thought to the obedience of Christ.” - 2 Corinthians 10:4-5 KJV', 'One of the greatest territories God has commanded every believer to subdue is the mind. Before you can subdue cities, systems, territories, or kingdoms, you must first subdue the thoughts that govern your life. Satan understands that a defeated mind will eventually produce a defeated life, even if the believer possesses great gifts and a powerful anointing. This is why he continually plants seeds of fear, doubt, inferiority, bitterness, lust, unbelief, condemnation, and hopelessness within the mind. These repeated thoughts eventually become strongholds—mental fortresses built by lies that oppose the truth of God''s Word.\n\nEvery stronghold begins with a thought that is entertained, believed, and repeated until it becomes a mindset. However, Genesis 1:28 declares that man was created to subdue, not to be subdued. Through the authority of Christ and the power of God''s Word, every imagination, every argument, and every thought that contradicts God''s purpose must be brought under the Lordship of Jesus Christ. Fellow Labourer in Christ, never allow your mind to become a battlefield where the enemy dictates the outcome.\n\nGuard what you read, what you watch, what you hear, and what you continually meditate upon because your thoughts eventually shape your words, your decisions, your habits, and your destiny. Fill your heart daily with the Scriptures until God''s truth becomes stronger than every negative voice from your past, your environment, or the kingdom of darkness. Refuse to rehearse failure when God has spoken victory. Reject every mindset of limitation when Heaven has declared fruitfulness and dominion over your life. Every day, arrest wrong thoughts before they become wrong beliefs and replace every lie with the truth of God''s Word. A mind governed by the Holy Spirit becomes an unconquerable fortress that no demonic attack can overthrow. When your mind is subdued under Christ, your life will naturally manifest the dominion of Genesis 1:28. Great Grace!', '["Romans 12:2", "Philippians 4:8", "Isaiah 26:3"]'::jsonb, 'You cannot consistently live above the level of your thinking; subdue your mind, and you will subdue your world.', 'I cast down every imagination and every stronghold contrary to the Word of God. My mind belongs to Christ. I reject fear, unbelief, anxiety, inferiority, and every limiting mindset. I think God''s thoughts, I speak God''s Word, and I walk in the dominion of Christ every day. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 17, 'Faithday 17th', 'The Authority of the Spoken Word', 'Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof. - Proverbs 18:21 KJV', 'From the beginning, God demonstrated that creation responds to spoken authority. Genesis 1 reveals that God did not build the world with His hands; He framed it with His Word. In the same way, man, created in His image, carries the ability to shape realities through words aligned with divine will. Genesis 1:28 begins with “And God said unto them…” showing that destiny is released through spoken instruction and covenant declaration. Words are not empty sounds; they are spiritual containers carrying either life or death, progress or limitation, blessing, or bondage. Fellow Labourer in Christ, guard your mouth diligently, for your future listens to your voice. Many are living below their inheritance, not because God withheld blessings but because their words contradicted His promises. Every time you speak fear, you rei nforce limitation. Every time you speak faith, you activate possibility. Let your speech align with Genesis 1:28 fruitfulness, multiplication, replenishment, subduing, and dominion. Speak life over your family, ministry, health, finances, and calling. Refuse negative confession even when circumstances disagree. The Word of God on your lips becomes the atmosphere in which your destiny grows. Great Grace!', '["James 3:2–6", "Mark 11:23–24", "Isaiah 55:11"]'::jsonb, 'Your life will eventually obey the words you consistently speak.', 'My tongue is an instrument of life. I speak fruitfulness, increase, restoration, and dominion. My words align with God’s purpose, and my destiny responds to my declarations in Christ Jesus. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 18, 'Sabbathday 18th', 'Dominion Over External Influences', 'And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God. - Roman 12:2 KJV', 'One of the greatest expressions of dominion is the ability to remain unmoved by ungodly external influences. The world is constantly attempting to shape the believer through peer pressure, social trends, cultural philosophies, media, and sinful lifestyles. Satan understands that if he cannot destroy your identity, he will attempt to redefine it through the cultures around you. This is why Apostle Paul commands believers not to be conformed to this world. The word "conformed" means to be pr essed into a mould or fashioned according to a pattern. Genesis 1:28 reveals that man was created to exercise dominion over the earth—not to be dominated by it. God''s original design was for man to influence his environment, not for the environment to influence him. Like No ah in a corrupt generation, Joseph in pagan Egypt, Daniel in Babylon, and the three Hebrew boys in a culture of idolatry, believers are called to stand firm in righteousness even when surrounded by compromise. Dominion is not proven when everything around you is holy; it is proven when darkness surrounds you, yet your light refuses to dim. Fellow Labourer in Christ, never permit the standards of society to become the standards of your life. Popular opinion is not the voice of God, and what is celebrated by culture may be condemned by Heaven. You have been called to be a thermostat that changes the atmosphere, not a thermometer that merely reflects it. Refuse the pressure to fit in at the expense of your convictions. Refuse friendships that weaken your consecration, entertainment that pollutes your spirit, conversations that corrupt your faith, and ambitions that draw you away from God''s purpose. The Holy Spirit has empowered you to live differently, think differently, and stand boldly for Christ without apology. As you continually renew your mind with God''s Word and cultivate intimacy with the Holy Spirit, you will develop the spiritual strength to resist every ungodly influence and become a living model of Kingdom culture. This is true dominion, not merely ruling over circumstances, but remaining unshaken in a generation determined to redefine truth. Great Grace!', '["Daniel 1:8", "Psalm 1:1–3", "1 John 2:15–17"]'::jsonb, 'A man who cannot resist the influence of the world cannot effectively exercise dominion in it.', 'I refuse to be conformed to the patterns of this world. I walk in Kingdom culture, and my life reflects the character of Christ. No peer pressure, evil culture, worldly philosophy, or ungodly influence shall derail my destiny. I influence my generation ins tead of being influenced by it. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 19, 'Sacredday 19th', 'Do Not Win Alone', '“Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow: but woe to him that is alone when he falleth; for he hath not another to help him up.” - Ecclesiastes 4:9–10 KJV', 'One of the greatest misconceptions about dominion is the belief that success is an individual pursuit. God''s first declaration over mankind was not to one person living in isolation but to humanity as a family. The mandate to "be fruitful, multiply, replenish, subdue, and have dominion" was too vast for one individual to fulfil alone. Kingdom dominion is designed to be collective.\n\nThroughout Scripture, God consistently demonstrates the power of partnership. Noah needed his family to preserve humanity. Moses needed Aaron and Hur to uphold his hands. David had mighty men who helped establish his kingdom. Jesus deliberately chose twelve disciples instead of ministering alone. The early Church transformed the world because believers laboured together in one accord. God''s greatest projects are rarely accomplished by isolated individuals; they are fulfilled through united labourers.\n\nFellow Labourer in Christ, reject the spirit of unhealthy independence. There is a difference between being self-reliant and being Spirit-led. Some opportunities, victories, and dimensions of influence will never manifest until you learn to walk with others in humility, honour, and unity. Do not see every gifted person as a competitor; many are divine partners assigned to strengthen your purpose. Celebrate the grace upon others instead of envying it. Learn to build people, encourage people, and collaborate with people. The Kingdom advances faster when gifted men and women work together. Remember, a victory shared with others produces generational impact, while a victory pursued alone often dies with the individual. Great Grace!', '["Exodus 17:11–13", "Mark 2:1–5", "Acts 2:44–47", "Philippians 1:27"]'::jsonb, 'Great destinies are rarely built alone; they are established through godly partnerships.', 'Father, deliver me from the spirit of isolation. Connect me with covenant, relationships, and faithful labourers. I shall not win alone, but together with those You have ordained, we shall accomplish great exploits for Your Kingdom, in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 20, 'Mercyday 20th', 'Be a Team Player', 'But now are they many members, yet but one body. And the eye cannot say unto the hand, I have no need of thee….....” - 1 Corinthians 12:20 –21 KJV', 'The human body is one of God''s greatest illustrations of teamwork. Every part is different, yet every part is necessary. The eye sees, but it cannot walk. The feet move, but they cannot hear. The heart pumps blood, but it cannot think. Each member depends upon the others for the body to function effectively. In the same way, the Body of Christ thrives through diversity operating in unity. The dominion mandate of Genesis 1:28 is too comprehensive for one gift, one ministry, or one individual. God intentionally distributes different gifts so that His people will need one another. Where honour exists among diverse graces, extraordinary results become possible. Fellow Labourer in Christ, embrace your place within God''s team. Do not become discouraged because your assignment differs from someone else''s. The Kingdom does not reward imitation; it rewards faithfulness. Your responsibility is not to become another person but to function excellently in the grace God has entrusted to you. Learn to celebrate the victories of others as though they were your own. Refuse jealousy, comparison, and unhealthy competition. Be dependable. Be teachable. Be supportive. The stronges t ministries, families, businesses, and churches are built by people who understand that the success of the whole is greater than the applause of one individual. God is looking for labourers who can work together without striving for personal glory. Great Grace!', '["Romans 12:4–8", "Ephesians 4:11–16", "Philippians 2:1–4", "1 Peter 4:10"]'::jsonb, 'The strength of a team is found in the unity of different gifts.', 'Lord, make me a faithful team player. Deliver me from pride, jealousy, and selfish ambition. Help me to serve with humility, honour every grace You have placed around me, and contribute faithfully to the success of Your Kingdom in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 21, 'Truthday 21st', 'Dominion Through Coalition', '“How should one chase a thousand, and two put ten thousand to flight, except their Rock had sold them, and the LORD had shut them up?” - Deuteronomy 32:30 KJV', 'One of the greatest mysteries of the Kingdom is the principle of spiritual synergy. God''s mathematics is different from human mathematics. One defeats a thousand, but two defeat ten thousand. The increase is not merely double. It is exponential. This is the power of covenant coalitions. When people are united by God''s purpose rather than personal ambition, Heaven releases multiplied strength, wisdom, favour, and authority. Throughout Scripture, divine coalitions changed history. Joshu a and Caleb stood togeth er in faith. Zerubbabel, Joshua, the high priest, and Haggai rebuilt the Temple. Paul worked with Barnabas, Silas, Timothy, Titus, Aquila, and Priscilla to establish churches across nations. The Kingdom expands most effectively when anointed people unite around a common vision. Fellow Labourer in Christ, pray for discernment to recognize your kingdom alliances. Not every relationship is covenant, but every destiny requires covenant relationships. God places strategic people in our lives to sharpen us, strengthen us, correct us, a nd help us fulfil our assignments. Never allow pride to destroy divine partnerships. Protect unity. Honour loyalty. Invest in relationships that advance God''s purpose. A healthy coalition does not weaken your identity; it strengthens your effectiveness. As you build and maintain godly alliances, you will accomplish exploits that would have been impossible alone. Together, the Church demonstrates the fullness of Christ and establishes His dominion upon the earth. Great Grace!', '["Amos 3:3", "Ecclesiastes 4:9–12", "Acts 13:1–3", "Hebrews 10:24–25"]'::jsonb, 'Kingdom coalitions produce exponential dominion where isolated effort produces limited results.', 'Father, surround me with covenant relationships and divine coalitions that advance your purpose. I receive wisdom to build, preserve, and honour kingdom partnerships. Together, we shall establish Your dominion and fulfil our divine assignments in Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 22, 'Wondersday 22nd', 'Little Drops Make an Ocean', 'For whom hath despised the day of small things? for they shall rejoice and shall see the plummet in the hand of Zerubbabel with those seven; they are the eyes of the LORD, which run to and fro through the whole earth.” - Zechariah 4:10 KJV ne of the greatest enemies of fruitfulness is the inability to appreciate small beginnings. God rarely begins with abundance; He often begins with a seed. The oak tree begins as an acorn, mighty rivers begin as tiny streams, and oceans are formed by countless drops of water. The Kingdom of God follows the same principle. Every great ministry, every successful business, every influential leader, and every extraordinary testimony once existed in a small, almost unnoticed form. Genesis 1:28 commands us to be f ruitful before multiplying because God first blesses what is small before He enlarges it. Those who continually complain about little blessings often delay the arrival of greater ones because gratitude is the language that attracts increase. Heaven entrust s much to those who honour little. When you celebrate one answered prayer, one open door, one soul won, one faithful friend, one opportunity, or one lesson learned, you are acknowledging that God is already at work in your life. Fellow Labourer in Christ, learn to celebrate every drop while believing for the ocean. Do not postpone your joy until the breakthrough becomes massive. Thank God for today''s strength while expecting tomorrow''s promotion. Rejoice over the little business t hat is growing, the small congregation that is increasing, the modest salary that feeds your family, the few opportunities that God has opened, and the little victories won in secret. Many people miss miracles because they are too occupied looking for spec tacular manifestations. Yet God''s greatest works often begin quietly. Gratitude transforms ordinary moments into sacred encounters. As you faithfully appreciate every little blessing, God will combine them into an overflowing testimony that generations will admire. Great Grace!', 'O', '["Luke 16:10", "Matthew 13:31–32", "Psalm 92:1–2", "1 Thessalonians 5:18"]'::jsonb, 'Those who honour little blessings qualify for greater ones.', 'I refuse to despise the day of small beginnings. I receive a grateful heart. Every little blessing in my life shall grow into extraordinary abundance. I celebrate every drop because I know God is preparing my ocean. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 23, 'Triumphday 23rd', 'The Grace of Compound Interest', 'Whatsoever thy hand findeth to do, do it with thy might...” - Ecclesiastes 9:10 KJV', 'One of God''s hidden laws for multiplication is the principle of consistent accumulation. In the financial world, compound interest causes small investments made consistently to become extraordinary wealth over time. The Kingdom of God operates in a similar way. Every prayer, every page of Scripture studied, every act of obedience, every soul won, every seed sown, every sacrifice made, every discipline embraced, and every day spent walking faithfully with God is never wasted. They accumulate in the spirit until they suddenly produce uncommon results. People often admire overnight success without realizing that Heaven has been adding unseen deposits for years. Noah built the ark one plank at a time. Joseph interpreted dreams faithfully before ruling Egypt. Davi d fought lions and bears before confronting Goliath. Their greatness was the product of accumulated obedience. Fellow Labourer in Christ, never underestimate the power of consistency. One prayer may seem insignificant, but ten thousand prayers create spiritual authority. One chapter of Scripture each day may appear small, but years of consistent study produce profound wisdom. One act of kindness may seem unnoticed, but repeated acts build a godly reputation. One day of discipline may appear ordinary, but disciplined years create extraordinary people. Continue adding daily deposits into your spiritual, intellectual, emotional, and financial life. The God of Genesis 1:28 delights in multiplication, and multiplication often comes through accumulated faithfulness rather than isolated moments of excitement. Keep sowing. Keep serving. Keep growing your compound harvest is closer than you think. Great Grace!', '["Galatians 6:9", "Hebrews 6:10", "Proverbs 13:11", "1 Corinthians 15:58"]'::jsonb, 'Consistency is the compound interest of destiny.', 'Every act of obedience accumulates into greatness. I receive grace for consistency. My daily investments in God shall produce extraordinary harvests. Nothing I do for Christ shall ever be wasted. Glory.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 24, 'Faithday 24th', 'Maintain The Quality Of Your Efforts', 'And whatsoever ye do, do it heartily, as to the Lord, and not unto men.” - Colossians 3:23 KJV', 'One of the subtle dangers that accompanies success is complacency. Many people pray fervently until God begins to bless them, but once testimonies become frequent, the quality of their effort begins to decline. They pray less, prepare less, study less, work less diligently, and become comfortable with yesterday''s victories. Yet the blessing of Genesis 1:28 was never intended to replace diligence; it was meant to empower it. God blesses excellence, consistency, and faithful stewardship. The same discipline that brought yesterday''s breakthrough is often required to sustain tomorrow''s increase. Harvest should never become an excuse to abandon cultivation. Fellow Labourer in Christ, never allow yesterday''s testimony to reduce today''s commitment. Continue praying with intensity. Continue studying with hunger. Continue preparing with excellence. Continue serving with humility. Continue giving your best even when people already celebrate you. Great men do not become great by occasional excellence but by maintaining high standards long after success has arrived. Remember that God watches not only beginnings but continuations. Your yield will always correspond to the quality of your cultivation. Therefore, refuse mediocrity. Refuse carelessness. Let every assignment, sermon, business transaction, conversation, and act of service reflect your best because you are ultimately serving the Lord. Great Grace!', '["Proverbs 22:29", "Ecclesiastes 9:10", "2 Timothy 2:15", "Matthew 25:21"]'::jsonb, 'What produced the harvest must be maintained to preserve the harvest.', 'I receive grace to maintain excellence. Success shall not make me careless, and testimonies shall not reduce my diligence. I shall continually give God my best in every assignment. Hallelujah.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 25, 'Sabbathday 25th', 'A Personality That Reflects The Blessing', 'A good name is rather to be chosen than great riches and loving favour rather than silver and gold.” - Proverbs 22:1 KJV', 'God''s blessing is not revealed only in what we possess but also in who we become. A truly blessed person should carry a personality that reflects the character of Christ. The blessing of Genesis 1:28 was given so that man would represent God on the earth, and representation begins with character before it reaches achievement. A harsh, arrogant, unapproachable, and dishonourable attitude contradicts the very nature of the God we claim to represent. Jesus possessed all authority in Heaven and on earth, yet He was approachable by children, compassionate toward sinners, patient with the weak, and gracious to the broken. Greatness in the Kingdom is measured not merely by influence but by the quality of one''s character. Fellow Labourer in Christ, let your personality become an advertisement of God''s goodness. Be warm in your greetings, sincere in your appreciation, gracious in your speech, approachable in your attitude, generous with encouragement, patient with people''s weaknesses, and humble despite your achievements. Let people encounter peace when they meet you. Let your smile restore hope, your words inspire courage, and your conduct reveal Christ. Never become so important that you forget kindness. Never become so suc cessful that you become inaccessible. The blessing of God should beautify your character as much as it enlarges your possessions. A beautiful personality opens doors that money, intelligence, and influence cannot open. May your life continually reflect the fragrance of Christ wherever you go. Great Grace!', '["Philippians 2:3 –5", "Colossians 4:6", "Ephesians 4:29 –32", "Matthew 11:29"]'::jsonb, 'Your character is the fragrance of the blessing you carry.', 'My life reflects the beauty of Christ. I am humble, gracious, joyful, approachable, compassionate, and full of wisdom. My personality attracts favour because it reveals the nature of my Father. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 26, 'Sacredday 26th', 'Hating Me Is Not Enough', '‘… So the wall was finished... And it came to pass, that when all our enemies heard thereof... they were much cast down in their own eyes: for they perceived that this work was wrought of our God.’ - Nehemiah6:15-16 KJV', 'One of the greatest misconceptions believers have is that opposition is proof that they have missed God. On the contrary, genuine Kingdom advancement often attracts resistance. The life of Nehemiah demonstrates that God''s assignment does not eliminate enemies; it exposes them. Sanballat, Tobiah, Geshem, and their allies mocked, threatened, lied, conspired, and attempted to distract Nehemiah from rebuilding Jerusalem''s walls. Yet every attack only amplified God''s glory because the opposition became undeniable evidence that the work was ordained by Heaven. The enemies unintentionally advertised Nehemiah''s relevance. If there had been nothing significant about his assignment, no one would have wasted time opposing him. This reveals a profound Kingdom mystery: ha tred cannot cancel what God has blessed. Genesis 1:28 begins with God''s blessing, and once God blesses a man, human hostility loses the power to reverse divine purpose. In fact, many times God uses opposition as the platform upon which He publicly reveals His power. Fellow Labourer in Christ, never become discouraged because of critics, envy, betrayal, or opposition. There are people whose assignment is to resist you, but even they remain servants of God''s sovereign purpose. Joseph''s brothers hated him, yet their hatr ed transported him to Egypt where his destiny awaited him. Pharaoh''s oppression multiplied Israel. Saul''s jealousy prepared David for the throne. The cross, designed to destroy Jesus, became the instrument of humanity''s redemption. This is why you must never spend your energy fighting haters. Stay focused on your assignment. Build while they criticize. Pray while they accuse. Advance while they conspire. Those who attempt to stop what God is doing in your life will eventually become witnesses of your testim ony. Remember this: haters cannot stop a man who is carrying the blessing of Genesis 1:28; they merely become unwilling participants in the fulfilment of his destiny. Great Grace!', '["Nehemiah 4:1–20", "Nehemiah 6:1–16", "Genesis 50:20", "Romans 8:28"]'::jsonb, 'When God blesses a man, even his enemies unknowingly contribute to his destiny.', 'The blessing of God upon my life cannot be reversed by the hatred of men. Every opposition works together for my advancement. I remain focused on my divine assignment, and every conspiracy against me shall ultimately glorify God. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 27, 'Mercyday 27th', 'Influencing Palaces', 'Seest thou a man diligent in his business? he shall stand before kings; he shall not stand before mean men. - Proverbs 22:29 KJV', 'God never intended His people to remain confined within church buildings. The dominion mandate of Genesis 1:28 extends into governments, boardrooms, royal courts, educational institutions, media, business, and every sphere where decisions shaping generations are made. Throughout Scripture, God consistently positioned His servants inside palaces. Joseph stood before Pharaoh and preserved nations. Daniel interpreted dreams before Nebuchadnezzar and Darius. Esther influenced the thro ne of Persia and rescued an entire people. Moses confronted Pharaoh with the authority of Heaven. Paul testified before governors, kings, and Caesar''s representatives. Their assignment was never merely to occupy positions but to bring Heaven''s culture into earthly governments. God ra ises Kingdom ambassadors who can speak truth without compromise and demonstrate excellence without losing consecration. Fellow Labourer in Christ, never underestimate where God is taking you. The excellence you cultivate today may become your passport into tomorrow''s palace. But remember, palaces are not destinations —they are platforms for Kingdom influence. If God places y ou before influential people, it is not merely for personal promotion but for divine representation. Let your wisdom reveal Christ. Let your integrity preach louder than your words. Let your solutions glorify God. Never hide your faith to gain acceptance, neither should you become arrogant because of influence. Carry the presence of God into every room you enter. The greatest victory is not merely entering the palace; it is ensuring that the King of kings is represented inside the palace through your life. Great Grace!', '["Daniel 2:46–49", "Esther 4:13–16", "Genesis 41:37–44", "Acts 26:1–29"]'::jsonb, 'God promotes His people into palaces so His Kingdom can influence kingdoms.', 'God opens doors that no man can shut. I stand before kings, leaders, and influential people as an ambassador of Christ. Through my life, God''s wisdom, righteousness, and Kingdom are established in high places. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 28, 'Truthday 28th', 'Leveraging The Gift Of Men', '‘Two are better than one; because they have a good reward for their labour. For if they fall, the one will lift up his fellow…’ - Ecclesiastes 4:9 - 10 KJV', 'One of God''s greatest gifts to destiny is people. While every believer must depend ultimately on God, God frequently chooses to answer prayers through human vessels. The dominion mandate in Genesis 1:28 was never designed to be fulfilled in isolation. Throughout Scripture, God connected people to people in order to advance His purposes. Moses had Aaron and Hur. David had Jonathan and his mighty men. Ruth had Boaz. Paul had Barnabas, Silas, Timothy, and Luke. Jesus Himself surrounded His ministry with disciples. Divine relationships are not accidents; they are strategic Kingdom provisions. Many doors do not open because of what you know alone, but because of who God has connected you to. There are dimensions of dominion that are unlocked through covenant relat ionships, wise counsel, mentorship, partnerships, and favour with men whom God has strategically positioned along your path. Fellow Labourer in Christ, never become so independent that you reject the gift of people. Honour those whom God sends into your life. Learn from mentors. Value spiritual fathers. Appreciate destiny helpers. Build relationships with integrity rather than m anipulation. Remember that favour cannot be demanded; it is attracted through character, humility, faithfulness, and excellence. Do not burn bridges that God may use tomorrow. Pray for discernment to recognize the people God has ordained for your next seas on, and equally strive to become a blessing in the lives of others. Sometimes your next level is not waiting for another miracle, it is waiting for the right relationship. When God blesses a man, He often sends another man carrying the key to his next door. Great Grace!', '["1 Samuel 18:1 –4", "Exodus 17:11 –13", "Romans 16:1 –16", "Philippians 2:19–22"]'::jsonb, 'God often hides your next level inside the life of another person.', 'Father, connect me with every relationship ordained for my destiny. I receive the gift of godly mentors, faithful partners, and divine helpers. Through covenant relationships, I fulfil my assignment and walk in dominion according to Your purpose. In Jesus'' Name. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 29, 'Wondersday 29th', 'The Lane Of Competition', '“But let every man prove his own work, and then shall he have rejoicing in himself alone, and not in another.” - Galatians 6:4 KJV', 'One of the most subtle destroyers of destiny is the spirit of comparison. It quietly shifts a believer from purpose to performance, from assignment to rivalry, and from divine assignment to human competition. Genesis 1:28 never called man to compete; it called man to be fruitful. Fruitfulness is identity -driven, not comparison-driven. The moment a believer begins to measure his life by another man’s field, speed, or results, he steps into a lane God never assigned to him. In the Kingdom, grace is distributed differently; assignments are unique, and timing is divine. What looks like delay may simply be alignment, and what looks like speed may not be covenant depth. God does not evaluate destinies by comparison but by obedience and faithfulness. Fellow Labourer in Christ, refuse to enter the toxic lane of competition. It drains joy, distorts purpose, and blinds you to your own progress. You are not in a race against men—you are in a walk with God. Your assignment carries its own grace, its own timing, and its own harvest. Celebrate others without feeling threatened; learn without envy; grow without comparison. Focus on your field, your instruction, and your stewardship. The day you master contentment in your assignment; you step into accelerated grace. Heaven does not reward comparison; it rewards faithfulness. Great Grace!', '["2 Corinthians 10:12", "John 21:21 –22", "Romans 12:6", "Philippians 4:11–13"]'::jsonb, 'Comparison is the thief of divine focus and gratitude.', 'I reject the spirit of comparison. I walk in my God -given assignment with joy and clarity. My life is not measured by others but by divine faithfulness. I flourish in my own grace and timing, in Jesus’ Name. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 30, 'Triumphday 30th', 'Subdue Systems, Not Men', '“For we wrestle not against flesh and blood, but against principalities, against powers…” - Ephesians 6:12 KJV', 'True dominion in Genesis 1:28 was never designed to be exercised over human beings but over systems, structures, and spiritual influences that resist God’s order. Man’s fall distorted dominion, causing men to dominate one another instead of governing creation under God. But in redemption, Christ restores correct authority; believers are called to subdue systems of darkness, not people created in God’s image. Systems include patterns of corruption, cycles of limitation, spiritual strongholds, cultural bondage, and environmental oppression. These are what resist destiny, not men. When a believer misidentifies the real enemy, he fights the wrong battles and loses spiritual authority. Fellow Labourer in Christ, shift your focus from human opposition to spiritual systems. Do not waste divine energy fighting people; learn to discern what spirit or system is influencing situations. The believer’s authority is most powerful when correctly directed. Through prayer, wisdom, and obedience, you dismantle systems of failure, delay, sin, and oppression. This is why Christ never attacked men. He confronted systems. As you grow in spiritual maturity, your prayers become strategic, your decisions bec ome precise, and your influence becomes transformational. Dominion is not control over people; it is transformation of environments under God’s authority. Great Grace!', '["Ephesians 6:12", "2 Corinthians 10:3 –5", "Luke 10:19", "Colossians 2:15"]'::jsonb, 'Mature dominion confronts systems, not people.', 'I subdue systems of darkness and resistance in the name of Jesus. I do not fight men; I enforce God’s order over structures and spiritual influences. My authority brings transformation and peace. Amen!'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;
insert into public.devotions (edition_id, day_number, weekday, title, scripture_reference, meditation, further_studies, wisdom_nugget, declaration)
select (select id from public.editions where slug = 'shiloh-july-2026'), 31, 'Faithday 31 st', 'For The Kingdom, For The Church', '“But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.” - Matthew 6:33 KJV', 'Genesis 1:28 reveals a blessed man, but Matthew 6:33 reveals the priority of that blessing, Kingdom advancement. The blessing upon a believer is never meant for self-glorification but for Kingdom expansion and Church edification. God blesses His people so that His purposes can be established in the earth. When the heart is aligned with the Kingdom, personal increase becomes a by-product of divine assignment. The Church is God’s visible expression on earth, and every believer is called to contribute to its gr owth through prayer, service, giving, and influence. Kingdom-centred living ensures that blessing flows through a man, not just to a man. Fellow Labourer in Christ, let your desire for increase be connected to Kingdom impact. Ask God to bless you not for vanity, but so you can strengthen His work, expand His Church, and advance His purpose in your generation. A Kingdom-focused life is a fruitful life. When your priorities align with God’s house, God aligns His hand with your life. Seek first His Kingdom, and watch Him establish your personal matters beyond struggle. This is the mystery of divine order —God prospers those who carry His agenda. Let your life become a channel of blessing to the Church worldwide, and your testimony will overflow with grace. Great Grace!', '["Matthew 6:33", "Haggai 1:8", "Acts 2:47", "Philippians 1:5"]'::jsonb, 'Kingdom priority transforms personal blessing into global impact.', 'I am blessed for Kingdom purpose. My life advances the Church of Jesus Christ. I prosper to support God’s work, and my increase serves eternal purposes. Amen.'
on conflict (edition_id, day_number) do update set
  weekday = excluded.weekday, title = excluded.title, scripture_reference = excluded.scripture_reference,
  meditation = excluded.meditation, further_studies = excluded.further_studies,
  wisdom_nugget = excluded.wisdom_nugget, declaration = excluded.declaration;

commit;
