import { StyleSheet } from 'react-native';
import { DewDesign } from '@/constants/design';

export const adminExtraStyles = StyleSheet.create({
  devotionList: { backgroundColor: DewDesign.colors.surface, borderRadius: 15, padding: 14, marginTop: 14, borderWidth: 1, borderColor: DewDesign.colors.line },
  devotionRow: { flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: DewDesign.colors.line, paddingVertical: 10 },
  dayBadge: { width: 32, height: 32, borderRadius: 10, backgroundColor: DewDesign.colors.forestSoft, alignItems: 'center', justifyContent: 'center' },
  dayBadgeText: { color: DewDesign.colors.forest, fontSize: 12, fontWeight: '900' },
  rowIcon: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  dateButton: { minHeight: 44, borderRadius: 10, backgroundColor: DewDesign.colors.forestSoft, flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 10, marginBottom: 9 },
  dateText: { color: DewDesign.colors.forest, fontSize: 12, fontWeight: '800' },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(30,42,36,0.62)', justifyContent: 'flex-end' },
  modalPanel: { maxHeight: '92%', backgroundColor: DewDesign.colors.canvas, borderTopLeftRadius: 22, borderTopRightRadius: 22, overflow: 'hidden', shadowColor: DewDesign.colors.ink, shadowOpacity: 0.18, shadowRadius: 18, shadowOffset: { width: 0, height: -5 }, elevation: 12 },
  modalScroll: { flexGrow: 0 },
  modalContent: { padding: 18, paddingBottom: 20 },
  modalHint: { minHeight: 28, borderTopWidth: 1, borderTopColor: DewDesign.colors.line, backgroundColor: DewDesign.colors.surface, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  modalHintText: { color: DewDesign.colors.muted, fontSize: 10, fontWeight: '700' },
  adminTabs: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 18 },
  adminTab: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11, borderRadius: 10, backgroundColor: DewDesign.colors.surfaceMuted },
  adminTabActive: { backgroundColor: DewDesign.colors.forest },
  adminTabText: { color: DewDesign.colors.forest, fontSize: 11, fontWeight: '900' },
  adminTabTextActive: { color: DewDesign.colors.white },
  adminPanel: { backgroundColor: DewDesign.colors.surface, borderRadius: 16, padding: 16, borderWidth: 1, borderColor: DewDesign.colors.line },
  panelIntro: { color: DewDesign.colors.body, fontSize: 13, lineHeight: 20, marginBottom: 16 },
  panelHeading: { color: DewDesign.colors.ink, fontSize: 15, fontWeight: '900', marginTop: 24, marginBottom: 8 },
  campaignRow: { flexDirection: 'row', alignItems: 'center', borderTopWidth: 1, borderTopColor: DewDesign.colors.line, paddingVertical: 11 },
  campaignIcon: { width: 34, height: 34, borderRadius: 10, backgroundColor: DewDesign.colors.terracottaSoft, alignItems: 'center', justifyContent: 'center' },
  sendButton: { width: 32, height: 32, borderRadius: 10, backgroundColor: DewDesign.colors.forest, alignItems: 'center', justifyContent: 'center' },
  deleteButton: { width: 32, height: 32, borderRadius: 10, backgroundColor: DewDesign.colors.terracottaSoft, alignItems: 'center', justifyContent: 'center' },
  dialogBackdrop: { flex: 1, backgroundColor: 'rgba(20,30,24,0.52)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  dialog: { width: '100%', maxWidth: 360, backgroundColor: DewDesign.colors.surface, borderRadius: 18, padding: 20, borderWidth: 1, borderColor: DewDesign.colors.line },
  dialogTitle: { color: DewDesign.colors.ink, fontSize: 20, fontWeight: '900' },
  dialogBody: { color: DewDesign.colors.body, fontSize: 14, lineHeight: 21, marginTop: 9 },
  dialogActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 9, marginTop: 20 },
  dialogCancel: { minHeight: 42, borderRadius: 10, backgroundColor: DewDesign.colors.surfaceMuted, paddingHorizontal: 15, justifyContent: 'center' },
  dialogCancelText: { color: DewDesign.colors.forest, fontWeight: '800' },
  dialogDelete: { minHeight: 42, borderRadius: 10, backgroundColor: DewDesign.colors.terracotta, paddingHorizontal: 15, justifyContent: 'center' },
  dialogDeleteText: { color: DewDesign.colors.white, fontWeight: '800' },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 9, marginBottom: 12 },
  metricCard: { width: '48%', flexGrow: 1, borderRadius: 12, padding: 13, backgroundColor: DewDesign.colors.forestSoft, minHeight: 74 },
  metricValue: { color: DewDesign.colors.forest, fontSize: 22, fontWeight: '900' },
  metricLabel: { color: DewDesign.colors.body, fontSize: 11, fontWeight: '700', marginTop: 3 },
  activityRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: DewDesign.colors.line, paddingVertical: 12 },
  panelButton: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 9, borderRadius: 11, backgroundColor: DewDesign.colors.surfaceMuted, paddingHorizontal: 13, marginBottom: 9 },
  panelButtonText: { color: DewDesign.colors.forest, fontSize: 13, fontWeight: '800' },
  roleNote: { color: DewDesign.colors.muted, fontSize: 12, marginTop: 10 },
});
